M  xp/bash-d/bin/raftpr

diff --git a/xp/bash-d/bin/raftpr b/xp/bash-d/bin/raftpr
--- a/xp/bash-d/bin/raftpr
+++ b/xp/bash-d/bin/raftpr
@@ -26,16 +26,34 @@ map_label()
     esac
 }
 
+map_base_branch()
+{
+    case $1 in
+        *7)
+            echo 'release-0.7'
+            ;;
+        *8)
+            echo 'release-0.8'
+            ;;
+        *9)
+            echo 'release-0.9'
+            ;;
+        *)
+            echo "invalid base branch: $1"
+            exit 1
+            ;;
+
+    esac
+}
+
 
 labels=""
 
 upstream_branch=main
-upstream="ups/$upstream_branch"
 
 branch=$(git symbolic-ref --short HEAD)
 echo "($branch)"
 title="$(git log -n1 --format='%s')"
-body="$(git log $upstream..HEAD --format='##### %s%n%+b%n')"
 
 case $1 in
     -l)
@@ -44,12 +62,20 @@ case $1 in
         labels="--label $lb"
         shift
         ;;
+    -b)
+        shift
+        upstream_branch="$(map_base_branch "$1")"
+        shift
+        ;;
     -t)
         shift
         title="$1"
         shift
     ;;
 esac
+
+upstream="ups/$upstream_branch"
+body="$(git log $upstream..HEAD --format='##### %s%n%+b%n')"
 
 c_feat=''
 c_fix=''
@@ -99,7 +125,12 @@ END
 # - Website
 # - Other
 
+echo "=== Merge to $upstream_branch"
+echo ""
+echo "=== Title:"
 echo "$title"
+echo ""
+echo "=== Body:"
 echo "$body"
 
 read -p "Continue? [y/n]" a
