fix git-split

diff --git a/xp/bash-d/plugin/git-multiplex/bin/git-cherry-rebase b/xp/bash-d/plugin/git-multiplex/bin/git-cherry-rebase
--- a/xp/bash-d/plugin/git-multiplex/bin/git-cherry-rebase
+++ b/xp/bash-d/plugin/git-multiplex/bin/git-cherry-rebase
@@ -49,7 +49,7 @@ debug()
 {
     if [ ".$_git_xp_verbose" = ".1" ]; then
         local LightCyan="$(tput bold ; tput setaf 6)"
-        log "$LightCyan" "$@"
+        log "$LightCyan" "$@" >&2
     fi
 }
 info()
@@ -163,6 +163,32 @@ git_branch_default_upstream()
 git_head_branch()
 {
     git symbolic-ref --short HEAD
+}
+
+git_copy_commit()
+{
+    # We're going to set some environment vars here, so
+    # do it in a subshell to get rid of them safely later
+    dd copy_commit "{$1}" "{$2}" "{$3}"
+    git log -1 --pretty=format:'%an%n%ae%n%ad%n%cn%n%ce%n%cd%n%s%n%n%b' "$1" |
+    (
+    read GIT_AUTHOR_NAME
+    read GIT_AUTHOR_EMAIL
+    read GIT_AUTHOR_DATE
+    read GIT_COMMITTER_NAME
+    read GIT_COMMITTER_EMAIL
+    read GIT_COMMITTER_DATE
+    export  GIT_AUTHOR_NAME \
+        GIT_AUTHOR_EMAIL \
+        GIT_AUTHOR_DATE \
+        GIT_COMMITTER_NAME \
+        GIT_COMMITTER_EMAIL \
+        GIT_COMMITTER_DATE
+
+    # (echo -n "$annotate"; cat ) |
+
+    git commit-tree "$2" $3  # reads the rest of stdin
+    ) || die "Can't copy commit $1"
 }
 #include '_git_xp_lib.sh' end
 
diff --git a/xp/bash-d/plugin/git-multiplex/bin/git-split b/xp/bash-d/plugin/git-multiplex/bin/git-split
--- a/xp/bash-d/plugin/git-multiplex/bin/git-split
+++ b/xp/bash-d/plugin/git-multiplex/bin/git-split
@@ -29,33 +29,238 @@
 # |/
 # * 82554be fix doc of Build
 
-usage()
+#include '_git_xp_lib.sh' begin
+#!/bin/sh
+
+_git_xp_verbose=1
+_git_log_before=''
+_git_log_after=''
+
+die()
 {
-    echo 'split files out of commits to build a new branch'
-    echo 'git-split [ -b <to-new-branch> ] <from>..[<to>] -- <fns>'
+    echo "Failure $@" >&2
     exit 1
 }
+die_empty()
+{
+    if test -z "$1"
+    then
+        shift
+        die empty: "$@"
+    fi
+}
 
-mes()
+set_verbose()
+{
+    _git_xp_verbose=${1-1}
+}
+
+log()
+{
+    local color="$1"
+    local title="$2"
+    shift
+    shift
+
+    local mes="$@"
+    local NC="$(tput sgr0)"
+
+    if [ -t 1 ]; then
+        title="${color}${title}${NC}"
+    fi
+    echo "$(eval "$_git_log_before")""$title $mes""$(eval "$_git_log_after")"
+}
+dd()
+{
+    debug "$@"
+}
+debug()
+{
+    if [ ".$_git_xp_verbose" = ".1" ]; then
+        local LightCyan="$(tput bold ; tput setaf 6)"
+        log "$LightCyan" "$@" >&2
+    fi
+}
+info()
 {
     local Brown="$(tput setaf 3)"
-    local NC="$(tput sgr0)"
-    echo $Brown"$@"$NC
+    log "$Brown" "$@"
 }
-
-githash()
+mes()
 {
-    git log -n1 --format="%H" $1
+    local Green="$(tput setaf 2)"
+    log "$Green" "$@"
+}
+ok() {
+    local Green="$(tput setaf 2)"
+    log "${Green}"  "ok:  $@"
+}
+err() {
+    local Red="$(tput setaf 1)"
+    log "${Red}"    "err: $@"
 }
 
-new_branch=
-while getopts "b:" opname; do
+_init_colors()
+{
+    Black="$(tput setaf 0)"
+    BlackBG="$(tput setab 0)"
+    DarkGrey="$(tput bold ; tput setaf 0)"
+    LightGrey="$(tput setaf 7)"
+    LightGreyBG="$(tput setab 7)"
+    White="$(tput bold ; tput setaf 7)"
+    Red="$(tput setaf 1)"
+    RedBG="$(tput setab 1)"
+    LightRed="$(tput bold ; tput setaf 1)"
+    Green="$(tput setaf 2)"
+    GreenBG="$(tput setab 2)"
+    LightGreen="$(tput bold ; tput setaf 2)"
+    Brown="$(tput setaf 3)"
+    BrownBG="$(tput setab 3)"
+    Yellow="$(tput bold ; tput setaf 3)"
+    Blue="$(tput setaf 4)"
+    BlueBG="$(tput setab 4)"
+    LightBlue="$(tput bold ; tput setaf 4)"
+    Purple="$(tput setaf 5)"
+    PurpleBG="$(tput setab 5)"
+    Pink="$(tput bold ; tput setaf 5)"
+    Cyan="$(tput setaf 6)"
+    CyanBG="$(tput setab 6)"
+    LightCyan="$(tput bold ; tput setaf 6)"
+    NC="$(tput sgr0)" # No Color
+}
+
+git_hash()
+{
+    git rev-parse $1 \
+        || die "'git_hash $@'"
+}
+git_is_merge()
+{
+    test $(git cat-file -p "$1" | grep "^parent " | wc -l) -gt 1
+}
+git_parents()
+{
+    git rev-list --parents -n 1 ${1-HEAD} | { read self parents; echo $parents; }
+}
+git_rev_list()
+{
+    # --parents
+    # print parent in this form:
+    #     <commit> <parent-1> <parent-2> ..
+
+    git rev-list \
+        --reverse \
+        --topo-order \
+        --default HEAD \
+        --simplify-merges \
+        "$@" \
+        || die "'git rev-list $@'"
+}
+git_tree_hash()
+{
+    git rev-parse "$1^{tree}"
+}
+git_ver()
+{
+    local git_version=$(git --version | awk '{print $NF}')
+    local git_version_1=${git_version%%.*}
+    local git_version_2=${git_version#*.}
+    git_version_2=${git_version_2%%.*}
+
+    printf "%03d%03d" $git_version_1 $git_version_2
+}
+git_working_root()
+{
+    git rev-parse --show-toplevel
+}
+
+git_branch_default_remote()
+{
+    local branchname=$1
+    git config --get branch.${branchname}.remote
+}
+git_branch_default_upstream_ref()
+{
+    local branchname=$1
+    git config --get branch.${branchname}.merge
+}
+git_branch_default_upstream()
+{
+    git_branch_default_upstream_ref "$@" | sed 's/^refs\/heads\///'
+}
+
+git_head_branch()
+{
+    git symbolic-ref --short HEAD
+}
+
+git_copy_commit()
+{
+    # We're going to set some environment vars here, so
+    # do it in a subshell to get rid of them safely later
+    dd copy_commit "{$1}" "{$2}" "{$3}"
+    git log -1 --pretty=format:'%an%n%ae%n%ad%n%cn%n%ce%n%cd%n%s%n%n%b' "$1" |
+    (
+    read GIT_AUTHOR_NAME
+    read GIT_AUTHOR_EMAIL
+    read GIT_AUTHOR_DATE
+    read GIT_COMMITTER_NAME
+    read GIT_COMMITTER_EMAIL
+    read GIT_COMMITTER_DATE
+    export  GIT_AUTHOR_NAME \
+        GIT_AUTHOR_EMAIL \
+        GIT_AUTHOR_DATE \
+        GIT_COMMITTER_NAME \
+        GIT_COMMITTER_EMAIL \
+        GIT_COMMITTER_DATE
+
+    # (echo -n "$annotate"; cat ) |
+
+    git commit-tree "$2" $3  # reads the rest of stdin
+    ) || die "Can't copy commit $1"
+}
+#include '_git_xp_lib.sh' end
+
+usage()
+{
+    cat <<-END
+usage: git-split [ -b <to-new-branch> ] [-r] [-m] <from>..[<to>] -- <fns>
+
+split files out of commits to build a new branch.
+
+options:
+
+    -b <new-branch>             create a new branch.
+
+    -r                          remove <fns> from original history.
+                                it changes history.
+
+    -m                          merge back new branch.
+END
+
+}
+
+new_branch=tmpbranch
+merge=0
+remove=0
+while getopts "b:mrh" opname; do
     case $opname in
         b)
             new_branch=$OPTARG
             ;;
+        m)
+            merge=1
+            ;;
+        r)
+            remove=1
+            ;;
+        h)
+            usage
+            exit 0
+            ;;
         [?])
             usage
+            exit 1
             ;;
     esac
 done
@@ -63,6 +268,7 @@ shift $(($OPTIND - 1))
 
 if [ ".$2" != ".--" ]; then
     usage
+    exit 1
 fi
 
 range=$1
@@ -73,6 +279,7 @@ fns="$@"
 base=${range%..*}
 if [ ".$base" = ".$range" ]; then
     usage
+    exit 1
 fi
 
 tip=${range#*..}
@@ -85,20 +292,24 @@ if [ ".$head" = "." ]; then
     head=$(git rev-parse HEAD)
 fi
 
-tip_hash=$(githash $tip)
+tip_hash=$(git_hash $tip)
 new_hash=
 merged_hash=
 
 
 extract()
 {
+    local parent=$1
+    local tree=
+    local commit=
+
     for c in $(git log --reverse $base..$tip_hash --format="%H" -- $fns); do
 
         mes "== to pick $fns from:"
         git --no-pager log --color --stat --decorate --pretty=oneline --abbrev-commit -M -n1 $c
         mes "== END =="
 
-        mes=$(git log -n1 --format="%B" $c)
+        # mes=$(git log -n1 --format="%B" $c)
 
         # force prefix when diff, since .gitconfig could hide prefix
         git diff --src-prefix=a/ --dst-prefix=b/ --binary $c~ $c -- $fns | git apply --index
@@ -107,20 +318,43 @@ extract()
         git status --short
         mes "== END =="
 
-        git commit -am "$mes"
+        # manually commit index
+
+        tree=$(git write-tree)
+
+        dd "tree to commit: $tree"
+        git ls-tree -r $tree
+        dd "end of tree"
+
+        dd parent: $parent
+
+        commit=$(git_copy_commit "$c" "$tree" "-p $parent")
+        dd "new commit:" $commit
+
+        git reset --hard $commit
+
+        parent=$commit
     done
     return 0
 }
 
 build_new_branch()
 {
-    git checkout --detach $base \
+    # git checkout --detach $base \
+    git checkout --orphan $new_branch \
+        && git reset --hard \
+        && git commit --allow-empty -m "init-root" \
+        && git clean -dxf \
         && mes "== build new branch ==" \
-        && extract \
-        && new_hash=$(githash) \
+        && mes "HEAD hash: $(git_hash HEAD)" \
+        && extract $(git_hash HEAD) \
+        && new_hash=$(git_hash HEAD) \
         && \
-        if [ ".$new_branch" != "." ]; then
-            git branch "$new_branch"
+        if [ "$new_branch" = "tmpbranch" ]; then
+            git checkout --detach HEAD \
+                && git branch -d tmpbranch
+        else
+            :
         fi \
         && mes "== new branch $new_branch hash is $new_hash == "
 }
@@ -150,12 +384,12 @@ merge_them()
 {
     mes "== merge splitted branch back to $tip ==" \
         && \
-        if [ ".$new_branch" = "." ]; then
+        if [ ".$new_branch" = "tmpbranch" ]; then
             git merge --commit --no-edit --no-ff $new_hash
         else
             git merge --commit --no-edit --no-ff $new_branch
         fi \
-        && merged_hash=$(githash) \
+        && merged_hash=$(git_hash) \
         && mes "merged hash: $merged_hash"
 }
 
@@ -185,7 +419,9 @@ update_tip_ref()
 
 mes "split $fns from $range" \
     && build_new_branch \
+    && { [ "$remove" = "0" ] && exit 0 || ``; } \
     && discard_changes \
+    && { [ "$merge" = "0" ] && exit 0 || ``; } \
     && merge_them \
     && is_same_as_original \
     && update_tip_ref \
