M  xp/bash-d/plugin/git-multiplex/bin/git-bci

diff --git a/xp/bash-d/plugin/git-multiplex/bin/git-split b/xp/bash-d/plugin/git-multiplex/bin/git-split
--- a/xp/bash-d/plugin/git-multiplex/bin/git-split
+++ b/xp/bash-d/plugin/git-multiplex/bin/git-split
@@ -172,7 +172,7 @@ log()
         title="${color}${title}${NC}"
         level="${color}${level}${NC}"
     fi
-    eval "echo \"$SHLIB_LOG_FORMAT\"" >&2
+    eval "echo \"$SHLIB_LOG_FORMAT\""
 }
 dd()
 {
@@ -261,7 +261,10 @@ git_branch_default_upstream_ref()
 }
 git_branch_default_upstream()
 {
-    git_branch_default_upstream_ref "$@" | sed 's/^refs\/heads\///'
+    git rev-parse --abbrev-ref --symbolic-full-name "$1"@{upstream}
+
+    # OR
+    # git_branch_default_upstream_ref "$@" | sed 's/^refs\/heads\///'
 }
 git_branch_exist()
 {
@@ -449,6 +452,38 @@ git_tree_add_blob()
         git ls-tree "$blob_treeish" "$blob_name" \
             | awk -v target_fn="$target_fn" -F"	" '{print $1"	"target_fn}'
     } | git mktree
+}
+
+git_workdir_save()
+{
+    local index_hash=$(git write-tree)
+
+    # add modified file to index and read index tree
+    git add -u
+    local working_hash=$(git write-tree)
+
+    # restore index tree
+    git read-tree $index_hash
+
+    echo $index_hash $working_hash
+}
+git_workdir_load()
+{
+    local index_hash=$1
+    local working_hash=$2
+
+    git_object_type $index_hash || die "invalid index hash: $index_hash"
+    git_object_type $working_hash || die "invalid workdir hash: $working_hash"
+
+    # First create a temp commit to restore working tree.
+    #
+    # git-read-index to index and git-reset does not work because deleted file in
+    # index does not apply to working tree.
+
+    local working_commit=$(echo "x" | git commit-tree $working_hash) || die get working commit
+    git reset --hard $working_commit || die reset to tmp commit
+    git reset --soft ORIG_HEAD || die reset to ORIG_HEAD
+    git read-tree $index_hash || die "load saved index tree from $index_hash"
 }
 
 git_copy_commit()
